### ISSUE TITLE
getting mongoose error in make

### ISSUE THREAD

**Issue by t4talole** [jpmens/qtripp#20]
`mongoose.c:1110:33: error: argument 1 of type 'unsigned char[16]' with mismatched bound [-Werror=array-parameter=]
 1110 | void cs_md5_final(unsigned char digest[16], cs_md5_ctx *ctx) {
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~
In file included from mongoose.c:1:
mongoose.h:1765:34: note: previously declared as 'unsigned char *'
 1765 | void cs_md5_final(unsigned char *md, cs_md5_ctx *c);
      |                   ~~~~~~~~~~~~~~~^~
cc1: all warnings being treated as errors
make: *** [<builtin>: mongoose.o] Error 1
`

**Comment by jpmens** [comment]
Thanks for the report. Which OS and compiler versions are you using?

**Comment by 128keaton** [comment]
I am having the same issue running gcc version 12.2.0 (Debian 12.2.0-14)

**Comment by jpmens** [comment]
Thanks for the report (and your patch). Could you please show us the compilation errors you saw **before** applying the patches?

**Comment by ckrey** [comment]
Before:
```shell
gcc -g -DMAXSPLITPARTS=500 -Idevices/ -I. -I/usr/local/include -Wall -Werror -DSTATSD   -c -o mongoose.o mongoose.c
mongoose.c:1110:33: error: argument 1 of type ‘unsigned char[16]’ with mismatched bound [-Werror=array-parameter=]
 1110 | void cs_md5_final(unsigned char digest[16], cs_md5_ctx *ctx) {
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~
In file included from mongoose.c:1:
mongoose.h:1765:34: note: previously declared as ‘unsigned char *’
 1765 | void cs_md5_final(unsigned char *md, cs_md5_ctx *c);
      |                   ~~~~~~~~~~~~~~~^~
cc1: all warnings being treated as errors
make: *** [<builtin>: mongoose.o] Error 1
```
